mybatis-flex:
  datasource:
    master:
      url: jdbc:mysql://127.0.0.1:3306/warlock?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
spring:
  quartz:
    job-store-type: jdbc  # 启用数据库存储
    jdbc:
#      initialize-schema: always  # 自动建表（首次启动时）
      initialize-schema: never  # 生产环境建议手动建表
    properties:
      org:
        quartz:
          scheduler:
            instanceName: WarlockScheduler
            instanceId: AUTO
          dataSource:
            myDS:
              driver: com.mysql.cj.jdbc.Driver
              URL: jdbc:mysql://127.0.0.1:3306/warlock?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
              user: root
              password: 123456
              # 使用 HikariCP 连接池配置
              provider: hikaricp
          threadPool:
            threadCount: 25
            threadPriority: 5
            class: org.quartz.simpl.SimpleThreadPool
  data:
    redis:
      host: 172.16.2.19
      port: 6379
      password: 3eCrAw8Ba6Tg
      database: 5

jwt:
  secret: 5oiR5piv5Lit5Zu95Lq677yM5oiR54ix5Lit5Zu944CCQ2hpbmEgTk8gMe+8gQ==
  access-token-validity: 43200000 #12h
  refresh-token-validity: 604800000 # 7d
# 文件传输配置 FileTransferConfiguration
transfer:
  slave:
    - "150622004499":
        host: 172.16.2.10
        port: 8841
        username: root
        password: zkah@123
        localPath: /app/files
        remotePath: /app/files
    - "150622020001":
        host: 172.16.2.15
        port: 8841
        username: root
        password: zkah@123
        localPath: /app/files
        remotePath: /home/app/ftp
    - "150622007792":
        host: 172.16.2.15
        port: 8841
        username: root
        password: zkah@123
        localPath: /app/files
        remotePath: /home/app/jg-ftp